include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    deprecated_member_use: ignore
    no_wildcard_variable_uses: ignore
    unnecessary_brace_in_string_interps: ignore
    use_super_parameters: ignore
